import React from 'react';
import QRCode from 'qrcode.react';
import { Timeline, ThemedScrollbars, DesktopWrapper, MobileWrapper, Clipboard, Icon } from '@deriv/components';
// import ObjectUtils from '@deriv/shared/utils/object';
// import StringUtils from '@deriv/shared/utils/string';
// import DateUtils from '@deriv/shared/utils/date';
import { localize, Localize } from '@deriv/translations';
import { WS } from 'Services/ws-methods';
import { connect } from 'Stores/connect';
import Article from './article.jsx';
import DigitForm from './digit-form.jsx';
import Loading from '../../../../../templates/app/components/loading.jsx';
import DemoMessage from '../../ErrorMessages/DemoMessage';
import LoadErrorMessage from '../../ErrorMessages/LoadErrorMessage';

class TwoFactorAuthentication extends React.Component {
    state = {
        is_two_factor_enabled: false,
        is_loading: true,
        error_message: '',
    };

    populateDigitResponse = response => {
        const {
            totp: { is_enabled },
        } = response.account_security;

        this.setState({ is_two_factor_enabled: is_enabled });

        return is_enabled;
    };

    getDigitStatus = async () => {
        const status_response = await WS.authorized.accountSecurity({ account_security: 1, totp_action: 'status' });
        if (status_response.error) {
            this.setState({ is_loading: false, error_message: status_response.error.message });
            return;
        }

        const is_enabled = this.populateDigitResponse(status_response);
        if (is_enabled) {
            this.setState({ is_loading: false });
        } else {
            const generate_response = await WS.authorized.accountSecurity({
                account_security: 1,
                totp_action: 'generate',
            });
            console.log(generate_response);
            this.setState({ is_loading: false });
        }
    };

    componentDidMount() {
        const { is_virtual } = this.props;
        if (is_virtual) {
            this.setState({ is_loading: false });
        } else {
            this.getDigitStatus();
        }
    }

    render() {
        const { is_loading, is_two_factor_enabled, error_message } = this.state;
        const { is_virtual, is_switching } = this.props;

        if (is_virtual) return <DemoMessage />;

        if (is_loading || is_switching) return <Loading is_fullscreen={false} className='account___intial-loader' />;

        if (error_message) return <LoadErrorMessage error_message={error_message} />;

        return (
            <section className='two-factor'>
                {is_two_factor_enabled ? (
                    <ThemedScrollbars autoHide className='two-factor__scrollbars' hideHorizontal={true}>
                        <div className='two-factor__wrapper--enabled'>
                            <Icon icon='IcQrPhone' className='two-factor__icon' />
                            <h3 className='two-factor__qr--title'>{localize('2FA enabled')}</h3>
                            <h4 className='two-factor__qr--message'>
                                {localize('You have enabled 2FA for your Deriv account.')}
                            </h4>
                            <h4 className='two-factor__qr--message'>
                                {localize(
                                    'To disable 2FA, please enter the six-digit authentication code generated by your 2FA app below:'
                                )}
                            </h4>
                            <DigitForm
                                is_enabled={is_two_factor_enabled}
                                populateDigitResponse={this.populateDigitResponse}
                            />
                        </div>
                    </ThemedScrollbars>
                ) : (
                    <div className='two-factor__wrapper'>
                        <ThemedScrollbars autoHide className='two-factor__scrollbars' hideHorizontal={true}>
                            <MobileWrapper>
                                <Article />
                            </MobileWrapper>
                            <h2 className='two-factor__title'>
                                {localize('How to set up 2FA for your Deriv account')}
                            </h2>

                            <Timeline className='two-factor__timeline'>
                                <Timeline.Item
                                    title={
                                        <Localize
                                            i18n_default_text='Scan the QR code below with your 2FA app. We recommend <0>Authy</0> or <0>Google Authenticator</0>. We do not support <0>Duo Mobile</0>.'
                                            components={[<strong key={0} />]}
                                        />
                                    }
                                >
                                    <div className='two-factor__qr'>
                                        <QRCode value='XXXXCCCXXXXXXX' />
                                        <h4 className='two-factor__qr--message'>
                                            {localize(
                                                'If you are unable to scan the QR code, you can manually enter this code instead:'
                                            )}
                                        </h4>
                                        <div className='two-factor__qr--code'>
                                            <span>XXXXCCCXXXXXXX</span>
                                            <Clipboard
                                                text_copy='XXXXCCCXXXXXXX'
                                                info_message='Click here to copy key'
                                                success_message='Key copied!'
                                                className='two-factor__qr--clipboard'
                                            />
                                        </div>
                                    </div>
                                </Timeline.Item>
                                <Timeline.Item
                                    title={localize('Enter the authentication code generated by your 2FA app:')}
                                >
                                    <DigitForm
                                        is_enabled={is_two_factor_enabled}
                                        populateDigitResponse={this.populateDigitResponse}
                                    />
                                </Timeline.Item>
                            </Timeline>
                        </ThemedScrollbars>
                        <DesktopWrapper>
                            <Article />
                        </DesktopWrapper>
                    </div>
                )}
            </section>
        );
    }
}

export default connect(({ client }) => ({
    is_virtual: client.is_virtual,
    is_switching: client.is_switching,
}))(TwoFactorAuthentication);
