name: invalidate_npm_cache
description: Invalidate the Master NPM cache
runs:
  using: composite
  steps:

  - name: save_cache
    uses: actions/cache/save@13aacd865c20de90d75de3b17ebe84f7a17d57d2
    with:
      path: node_modules
      key: ${{ runner.os }}-build-master-cache-${{ hashFiles('./package-lock.json') }}
