const routes = {
    error404            : '/404',
    account             : '/account',
    financial_assessment: '/account/financial_assessment',
    personal_details    : '/account/personal_details',
    account_limits      : '/account/account_limits',
    account_password    : '/settings/account_password',
    apps                : '/settings/apps',
    cashier_password    : '/settings/cashier_password',
    contract            : '/contract/:contract_id',
    exclusion           : '/settings/exclusion',
    financial           : '/settings/financial',
    history             : '/settings/history',
    index               : '/index',
    limits              : '/settings/limits',
    personal            : '/settings/personal',
    positions           : '/reports/positions',
    profit              : '/reports/profit',
    reports             : '/reports',
    root                : '/',
    redirect            : '/redirect',
    settings            : '/settings',
    statement           : '/reports/statement',
    token               : '/settings/token',
    trade               : '/',
};

export default routes;
