const routes = {
    root                : '/',
    trade               : '/',
    error404            : '/404',
    account             : '/account',
    financial_assessment: '/account/financial-assessment',
    personal_details    : '/account/personal-details',
    proof_of_identity   : '/account/proof-of-identity',
    proof_of_address    : '/account/proof-of-address',
    deriv_password      : '/account/deriv-password',
    account_limits      : '/account/account-limits',
    contract            : '/contract/:contract_id',
    index               : '/index',
    mt5                 : '/mt5',
    otc                 : '/otc',
    otc_ads             : '/otc/ads',
    otc_buy_sell        : '/otc/buy-sell',
    otc_my_profile      : '/otc/my-profile',
    otc_orders          : '/otc/orders',
    otc_order           : '/otc/order/:order_id',
    otc_profile         : '/otc/profile/:profile_id',
    redirect            : '/redirect',
    reports             : '/reports',
    positions           : '/reports/positions',
    profit              : '/reports/profit',
    statement           : '/reports/statement',
    settings            : '/settings',
    apps                : '/settings/apps',
    account_password    : '/settings/account_password',
    cashier_password    : '/settings/cashier_password',
    exclusion           : '/settings/exclusion',
    financial           : '/settings/financial',
    history             : '/settings/history',
    limits              : '/settings/limits',
    personal            : '/settings/personal',
    token               : '/settings/token',
};

export default routes;
