labelPRBasedOnFilePath:
  Account:
    - packages/account/**/*
  Bot:
    - packages/bot-*/**/*
  Components:
    - packages/components/**/*
  Core:
    - packages/core/**/*
  Dashboard:
    - packages/dashboard/**/*
  P2P:
    - packages/p2p/**/*
  Shared:
    - packages/shared/**/*
  Trader:
    - packages/trader/**/*
  Translations:
    - packages/translations/**/*
  Docs:
    - README.md
    - docs/**/*.md
    - packages/**/*.md
