/* eslint-disable import/extensions */
import './block.js';
import './block_render_svg_vertical.js';
import './block_svg.js';
import './colours.js';
import './connection.js';
import './constant.js';
import './contextmenu.js';
import './css.js';
import './data_category.js';
import './field_dropdown.js';
import './field.js';
import './field_image.js';
import './flyout_base.js';
import './gesture.js';
import './icon.js';
import './procedures.js';
// import './toolbox.js';
import './trashcan.js';
import './variable_map.js';
import './variables.js';
import './workspace.js';
import './workspace_audio.js';
import './workspace_svg.js';
import './xml.js';
import './field_textinput.js';
