// This is an auto-generated list of strings used in js code for debugging purpose only
module.exports = [
    'API Token',
    'API token for third party applications',
    'Account Limits',
    'Account Password',
    'Action',
    'Amount is a required field.',
    'Apr',
    'Are you sure you want to purchase this contract?',
    'Asian Down',
    'Asian Up',
    'Asians',
    'Asset Information',
    'Aug',
    'Authorized Applications',
    'Balance',
    'Barrier',
    'Barrier is a required field.',
    'Barriers',
    'Buy Price',
    'Cancel',
    'Cashier Password',
    'Change the password used for deposits and withdrawals',
    'Change your main login password.',
    'Chart',
    'Close-Low',
    'Connecting to server',
    'Contract Details',
    'Contract Expiry',
    'Contract ID',
    'Contract Information',
    'Contract Lost',
    'Contract Purchased',
    'Contract Type',
    'Contract Won',
    'Contract will be sold at the prevailing market price when the request is received by our servers. This price may differ from the indicated price.',
    'Create one now',
    'Credit/Debit',
    'Crypto',
    'DEMO',
    'Dark Mode',
    'Date',
    'Dec',
    'Demo',
    'Deposit',
    'Description',
    'Digit Differs',
    'Digit Even',
    'Digit Matches',
    'Digit Odd',
    'Digit Over',
    'Digit Under',
    'Digits',
    'Does Not Touch',
    'Don\'t have a [_1] account?',
    'Duration',
    'Duration is a required field.',
    'End Time',
    'End date',
    'Ends Between',
    'Ends Between/Ends Outside',
    'Ends Outside',
    'Entry Spot',
    'Even/Odd',
    'Exit Spot',
    'Exit Spot Time',
    'Facility that allows you to set limits on your account.',
    'Feb',
    'Fiat',
    'Filter by date:',
    'Financial Assessment',
    'General',
    'Goes Outside',
    'High-Close',
    'High-Low',
    'Higher',
    'Higher barrier must be higher than lower barrier.',
    'Higher or equal',
    'Higher/Lower',
    'Hint: it would take approximately [_1][_2] to crack this password.',
    'Hour',
    'In/Out',
    'Indicative',
    'Indicative Price',
    'Invalid email address.',
    'Invest Amount',
    'Jan',
    'Jul',
    'Jun',
    'Language',
    'Last Digit',
    'Last Digit Prediction',
    'Limits',
    'Log in',
    'Log out',
    'Login History',
    'Logout',
    'Lower',
    'Lower barrier must be lower than higher barrier.',
    'Lower or equal',
    'Manage your authorised applications',
    'Mar',
    'Matches/Differs',
    'May',
    'Minimum of [_1] characters required.',
    'Minute',
    'Multiplier',
    'Net Profit',
    'Network status: [_1]',
    'No Notifications',
    'No open positions.',
    'Nov',
    'Now',
    'Oct',
    'Only letters, numbers, space, and hyphen are allowed.',
    'Only letters, numbers, space, and these special characters are allowed: [_1]',
    'Only letters, numbers, space, hyphen, period, and apostrophe are allowed.',
    'Only letters, space, hyphen, period, and apostrophe are allowed.',
    'Only numbers and spaces are allowed.',
    'Only numbers and these special characters are allowed: [_1]',
    'Over/Under',
    'Password should have lower and uppercase letters with numbers.',
    'Payout',
    'Personal Details',
    'Please log in to purchase the contract',
    'Portfolio',
    'Portfolio Quick Menu',
    'Position',
    'Potential Payout',
    'Profile',
    'Profit/Loss',
    'Purchase',
    'Purchase Confirmation',
    'Purchase Info',
    'Purchase Lock',
    'Purchase Locked',
    'Purchase Price',
    'Purchase Time',
    'Ref.',
    'Reference No.',
    'Reference No:',
    'Remaining Time',
    'Resale not offered',
    'Return',
    'Rise/Fall',
    'Scale Countdown',
    'Security & Limits',
    'Select a duration',
    'Select date',
    'Select time',
    'Self Exclusion',
    'Sell',
    'Sep',
    'Settings',
    'Should be [_1]',
    'Should be a valid number.',
    'Should be between [_1] and [_2]',
    'Should be less than [_1]',
    'Should be more than [_1]',
    'Should start with letter or number, and may contain hyphen and underscore.',
    'Sorry, an error occured while processing your request.',
    'Stake',
    'Start',
    'Start Time',
    'Start a new trade',
    'Start date',
    'Start time',
    'Statement',
    'Stays Between',
    'Stays Between/Goes Outside',
    'The length of token should be 8.',
    'The minimum duration is [_1] day',
    'The minimum duration is [_1] days',
    'The password you entered is one of the world\'s most commonly used passwords. You should not be using this password.',
    'The two passwords that you entered do not match.',
    'Tick [_1]',
    'Today',
    'Total',
    'Touch/No Touch',
    'Touches',
    'Trade',
    'Trade Duration',
    'Trade now',
    'Transaction ID',
    'Unknown Error!',
    'Unlock',
    'Up to [_1] decimal places are allowed.',
    'Up/Down',
    'Upgrade',
    'Validate address',
    'View your financial assessment settings',
    'View your login history',
    'View your personal information.',
    'View your trading and withdrawal limits',
    'You can lock/unlock the purchase button from the Settings menu',
    'You have an insufficient amount of balance.',
    'You have yet to receive any notifications',
    'You should enter [_1] characters.',
    'Your account has no trading activity for the selected period.',
    'Your account has no trading activity.',
    'Your transaction reference number is [_1]',
    '[_1] Account',
    '[_1] and [_2] cannot be the same.',
    'all notifications',
    'day',
    'days',
    'hours',
    'language',
    'log in',
    'million',
    'minutes',
    'seconds',
    'thousand',
    'ticks',
    'years',
];
