// This is an auto-generated list of strings used in js code for debugging purpose only
module.exports = [
    'API Token',
    'API token for third party applications',
    'Account Authentication',
    'Account Limits',
    'Account Password',
    'Action',
    'Add new account',
    'Allow equals',
    'Amount is a required field.',
    'Apr',
    'Asian Down',
    'Asian Up',
    'Asian options settle by comparing the last tick with the average spot over the period.',
    'Asians',
    'Aug',
    'Authentication Failed',
    'Authorized Applications',
    'BETA',
    'Back to main website',
    'Balance',
    'Barrier',
    'Barrier is a required field.',
    'Barriers',
    'Binary Coin',
    'Binary Options Trading Disabled',
    'Bitcoin',
    'Bitcoin Cash',
    'Both barriers should be relative or absolute',
    'Buy price',
    'Buy time',
    'Call Spread',
    'Cashier Disabled',
    'Cashier Password',
    'Certain trade parameters have been changed due to your account settings.',
    'Change the password used for deposits and withdrawals',
    'Change your main login password.',
    'Charts',
    'Choose',
    'Close',
    'Close-Low',
    'Complete your personal details',
    'Connecting to server',
    'Continue with Virtual Account',
    'Contract Details',
    'Contract Expiry',
    'Contract Information',
    'Contract Lost',
    'Contract Purchased',
    'Contract Type',
    'Contract Won',
    'Contract does not exist or does not belong to this client.',
    'Contract sold',
    'Contract will be sold at the prevailing market price when the request is received by our servers. This price may differ from the indicated price.',
    'Could not switch to default account.',
    'Credit/Debit',
    'Crypto',
    'DEMO',
    'Dark Mode',
    'Date',
    'Day',
    'Days',
    'Dec',
    'Deposit',
    'Deposits and withdrawals have been disabled on your account. Please check your email for more details.',
    'Description',
    'Description not found.',
    'Differs',
    'Digits',
    'Display remaining time for each interval',
    'Documents in review',
    'Duration',
    'Duration is a required field.',
    'Duration: ',
    'End Time',
    'End date',
    'End time',
    'Ends Between',
    'Ends Between/Ends Outside',
    'Ends Outside',
    'Entry Spot',
    'Entry spot',
    'Equals [_1]',
    'Error 404',
    'Error Code: [_1]',
    'Ether',
    'Ether Classic',
    'Even',
    'Even/Odd',
    'Exit Spot',
    'Exit Spot Time',
    'Exit spot',
    'Expiry time cannot be in the past.',
    'F',
    'Facility that allows you to set limits on your account.',
    'Fall',
    'Feb',
    'Fiat',
    'Filter by date:',
    'Financial Assessment',
    'Friday',
    'Gaming',
    'Go to Reports',
    'Go to SmartTrader',
    'Goes Outside',
    'High Tick',
    'High-Close',
    'High-Low',
    'Higher',
    'Higher barrier must be higher than lower barrier.',
    'Higher/Lower',
    'Hour',
    'Hour must be between 0 and 23.',
    'If the exit spot is equal to either the Low barrier or the High barrier, you don\'t win the payout.',
    'If the exit spot is equal to the barrier, you don\'t win the payout.',
    'If the last tick is equal to the average of the ticks, you don\'t win the payout.',
    'If you have an account, log in to continue.',
    'If you select "Allow equals", you win the payout if exit spot is higher than or equal to entry spot for "Rise". Similarly, you win the payout if exit spot is lower than or equal to entry spot for "Fall".',
    'If you select "Asian Fall", you will win the payout if the last tick is lower than the average of the ticks.',
    'If you select "Asian Rise", you will win the payout if the last tick is higher than the average of the ticks.',
    'If you select "Differs", you will win the payout if the last digit of the last tick is not the same as your prediction.',
    'If you select "Ends Between", you win the payout if the exit spot is strictly higher than the Low barrier AND strictly lower than the High barrier.',
    'If you select "Ends Outside", you win the payout if the exit spot is EITHER strictly higher than the High barrier, OR strictly lower than the Low barrier.',
    'If you select "Even", you will win the payout if the last digit of the last tick is an even number (i.e., 2, 4, 6, 8, or 0).',
    'If you select "Fall", you win the payout if the exit spot is strictly lower than the entry spot.',
    'If you select "Goes Outside", you win the payout if the market touches either the High barrier or the Low barrier at any time during the contract period.',
    'If you select "Higher", you win the payout if the exit spot is strictly higher than the barrier.',
    'If you select "Lower", you win the payout if the exit spot is strictly lower than the barrier.',
    'If you select "Matches", you will win the payout if the last digit of the last tick is the same as your prediction.',
    'If you select "No Touch", you win the payout if the market never touches the barrier at any time during the contract period.',
    'If you select "Odd", you will win the payout if the last digit of the last tick is an odd number (i.e., 1, 3, 5, 7, or 9).',
    'If you select "Over", you will win the payout if the last digit of the last tick is greater than your prediction.',
    'If you select "Rise", you win the payout if the exit spot is strictly higher than the entry spot.',
    'If you select "Stays Between", you win the payout if the market stays between (does not touch) either the High barrier or the Low barrier at any time during the contract period',
    'If you select "Touch", you win the payout if the market touches the barrier at any time during the contract period.',
    'If you select "Under", you will win the payout if the last digit of the last tick is less than your prediction.',
    'In/Out',
    'Indicative',
    'Indicative Price',
    'Indicative Price:',
    'Indicative price',
    'Install [_1] app?',
    'Invalid email address.',
    'Investment',
    'Jan',
    'Jul',
    'Jun',
    'Language',
    'Last Digit',
    'Last Digit Prediction',
    'Limits',
    'Litecoin',
    'Log in',
    'Log out',
    'Login History',
    'Logout',
    'Low Tick',
    'Lower',
    'Lower barrier must be lower than higher barrier.',
    'M',
    'MT5 Withdrawal Disabled',
    'MT5 withdrawals have been disabled on your account. Please check your email for more details.',
    'Manage your authorised applications',
    'Mar',
    'Market is unavailable',
    'Matches',
    'Matches/Differs',
    'May',
    'Minimum duration is 1 day',
    'Minimum of [_1] characters required.',
    'Minute',
    'Minute must be between 0 and 59.',
    'Monday',
    'Multiplier',
    'Network status: [_1]',
    'No',
    'No Notifications',
    'No Touch',
    'No open positions',
    'No, stay on Deriv',
    'Not [_1]',
    'Nov',
    'Now',
    'OK',
    'Oct',
    'Odd',
    'Offline',
    'Online',
    'Only Downs',
    'Only Ups',
    'Only letters, numbers, space, and hyphen are allowed.',
    'Only letters, numbers, space, and these special characters are allowed: [_1]',
    'Only letters, numbers, space, hyphen, period, and apostrophe are allowed.',
    'Only letters, space, hyphen, period, and apostrophe are allowed.',
    'Only numbers and spaces are allowed.',
    'Only numbers and these special characters are allowed: [_1]',
    'Oops, page not available.',
    'Oops, something went wrong.',
    'Open Positions',
    'Open positions',
    'Over',
    'Over [_1]',
    'Over/Under',
    'P/L:',
    'Password should have lower and uppercase letters with numbers.',
    'Payout',
    'Payout:',
    'Personal Details',
    'Platform settings',
    'Please enter the start time in the format "HH:MM".',
    'Please refresh this page to continue.',
    'Portfolio',
    'Potential P/L:',
    'Potential Payout',
    'Potential payout',
    'Profile',
    'Profit Table',
    'Profit table',
    'Profit/Loss',
    'Purchase',
    'Purchase Error',
    'Purchase Price',
    'Purchase Time',
    'Purchase price',
    'Put Spread',
    'Real',
    'Real account',
    'Real accounts',
    'Ref.',
    'Ref. ID',
    'Ref. ID (Buy)',
    'Ref. ID (Sell)',
    'Reference No.',
    'Reference No:',
    'Refresh',
    'Remaining Time',
    'Remaining time',
    'Remove Deposit Limits',
    'Reports',
    'Resale not offered',
    'Reset Call',
    'Reset Put',
    'Return to Trade',
    'Rise',
    'Rise/Fall',
    'S',
    'Saturday',
    'Security & Limits',
    'Select a date',
    'Self Exclusion',
    'Self-exclusion Detected',
    'Sell',
    'Sell Error',
    'Sell contract',
    'Sell price',
    'Sell time',
    'Sep',
    'Set Currency',
    'Should be [_1]',
    'Should be a valid number.',
    'Should be between [_1] and [_2]',
    'Should be less than [_1]',
    'Should be more than [_1]',
    'Should start with letter or number, and may contain hyphen and underscore.',
    'Sign up',
    'Sorry, an error occured while processing your request.',
    'Sorry, this app is unavailable in [_1].',
    'Sorry, this app is unavailable in your current location.',
    'Stake',
    'Start Time',
    'Start a new trade',
    'Start date',
    'Start time',
    'Start time cannot be in the past.',
    'Statement',
    'Stays Between',
    'Stays Between/Goes Outside',
    'Sunday',
    'Switching to default account.',
    'T',
    'Take me to SmartTrader',
    'Target',
    'Terms & Conditions Updated',
    'Tether',
    'The length of token should be 8.',
    'The page you requested could not be found. Either it no longer exists or the address is wrong. Please check for any typos.',
    'The two passwords that you entered do not match.',
    'Themes',
    'Thursday',
    'Tick [_1]',
    'Total',
    'Total profit/loss',
    'Touch',
    'Touch/No Touch',
    'Trade',
    'Trade now',
    'Trading and Deposits Disabled',
    'Trading is unavailable at this time.',
    'Transaction',
    'Transaction time',
    'Tuesday',
    'Under',
    'Under [_1]',
    'Up to [_1] decimal places are allowed.',
    'Up/Down',
    'Upgrade',
    'Upgrade to Real Account',
    'View all active trades on your account that can still incur a profit or a loss.',
    'View all trades purchased on your account, and a summary of your total profit/loss.',
    'View all transactions on your account, including trades, deposits, and withdrawals.',
    'View your financial assessment settings',
    'View your login history',
    'View your personal information.',
    'View your trading and withdrawal limits',
    'Virtual',
    'Virtual account',
    'W',
    'Wednesday',
    'Whoops!',
    'Win payout if exit spot is also equal to entry spot.',
    'Withdrawal Disabled',
    'Withdrawal and Trading Limits',
    'Withdrawals have been disabled on your account. Please check your email for more details.',
    'Yes',
    'You have no open positions yet.',
    'You have no trading activity for this period.',
    'You have no trading activity yet.',
    'You have no transactions for this period.',
    'You have no transactions yet.',
    'You have yet to receive any notifications',
    'You should enter [_1] characters.',
    'Your account has no trading activity for the selected period.',
    'Your account has no trading activity.',
    'Your transaction reference number is [_1]',
    '[_1]',
    '[_1] Tick',
    '[_1] Ticks',
    '[_1] and [_2] cannot be the same.',
    'all notifications',
    'day',
    'days',
    'hour',
    'hours',
    'lost',
    'minute',
    'minutes',
    'seconds',
    'tick',
    'ticks',
    'won',
];
