// This is an auto-generated list of strings used in js code for debugging purpose only
module.exports = [
    'AM',
    'Account',
    'Account Authenticated',
    'Account balance:',
    'Accounts List',
    'Acknowledge',
    'Action',
    'Add +/– to define a barrier offset. For example, +0.005 means a barrier that\'s 0.005 higher than the entry spot.',
    'Adjust trade parameters',
    'Admin',
    'Advanced',
    'All barriers in this trading window are expired',
    'Amount',
    'Amount in',
    'An additional password can be used to restrict access to the cashier.',
    'Apply now as a professional investor',
    'Apr',
    'April',
    'Are you sure that you want to permanently delete the token',
    'Are you sure that you want to permanently revoke access to the application',
    'Are you sure you want to create a fiat account in [_1]?',
    'Are you sure you want to create your [_1] account now?',
    'Are you sure?',
    'Asian Down',
    'Asian Up',
    'Asset',
    'Audit',
    'Audit Page',
    'Aug',
    'August',
    'Available Currencies',
    'Available Markets',
    'Average',
    'Balance',
    'Barrier',
    'Barrier Change',
    'Bid',
    'Binary Coin',
    'Binary Options Trading has been disabled on your account. Kindly [_1]contact customer support[_2] for assistance.',
    'Bitcoin',
    'Bitcoin Cash',
    'Browser',
    'Buy',
    'Buy price',
    'Call Spread',
    'Cancel',
    'Change',
    'Change Password',
    'Chart is not available for this underlying.',
    'Charting for this underlying is delayed',
    'Checked',
    'Checking',
    'Click OK to proceed.',
    'Click here to open a Financial Account',
    'Click here to open a Real Account',
    'Close',
    'Close Time',
    'Close-Low',
    'Closed Bid',
    'Closes',
    'Commodities',
    'Compressing Image',
    'Connecting to server',
    'Connection error: Please check your internet connection.',
    'Continue trading',
    'Contract',
    'Contract Confirmation',
    'Contract Details',
    'Contract Ends',
    'Contract Information',
    'Contract Result',
    'Contract Starts',
    'Contract Type',
    'Contract has not started yet',
    'Contract will be sold at the prevailing market price when the request is received by our servers. This price may differ from the indicated price.',
    'Counterparty',
    'Country of Residence',
    'Create',
    'Create Account',
    'Create [_1] account',
    'Credit/Debit',
    'Crypto',
    'Currency',
    'Current',
    'Current Time',
    'Current password',
    'Date',
    'Date and Time',
    'Day',
    'Days',
    'Dec',
    'December',
    'Delete',
    'Demo Account',
    'Demo Accounts',
    'Demo Advanced',
    'Demo Standard',
    'Demo Volatility Indices',
    'Deposit',
    'Deposits and withdrawals have been disabled on your account. Please check your email for more details.',
    'Description',
    'Details',
    'Digit',
    'Digit Differs',
    'Digit Even',
    'Digit Matches',
    'Digit Odd',
    'Digit Over',
    'Digit Under',
    'Disable',
    'Do you want this to be a fiat account or crypto account? Please choose one:',
    'Do you wish to continue?',
    'Does Not Touch',
    'Don\'t want to trade in [_1]? You can open another cryptocurrency account.',
    'Driving licence',
    'Duration',
    'Email address',
    'Enable',
    'End Time',
    'Ends Between',
    'Ends Outside',
    'Entry Spot',
    'Equals',
    'Ether',
    'Ether Classic',
    'Even/Odd',
    'Exclude time cannot be for more than 5 years.',
    'Exclude time cannot be less than 6 months.',
    'Excluded from the website until',
    'Exit Spot',
    'Exit Spot Time',
    'Expiry date is required for [_1].',
    'Failed',
    'Feb',
    'February',
    'Fiat',
    'File ([_1]) size exceeds the permitted limit. Maximum allowed file size: [_2]',
    'Final price',
    'Financial Account',
    'Finish',
    'First line of home address',
    'Forex',
    'Fr',
    'Friday',
    'From account: ',
    'Front Side',
    'Front and reverse side photos of [_1] are required.',
    'Gaming',
    'Get [_1]',
    'Go to statement',
    'Goes Outside',
    'Guide',
    'High',
    'High Barrier',
    'High Tick',
    'High-Close',
    'High-Low',
    'Higher',
    'Higher or equal',
    'Higher/Lower',
    'Hint: it would take approximately [_1][_2] to crack this password.',
    'Hour',
    'Hours',
    'I want to reapply',
    'ID number is required for [_1].',
    'IP Address',
    'Identity card',
    'In the EU, financial binary options are only available to professional investors.',
    'In/Out',
    'Indicates required field',
    'Indicative',
    'Indices',
    'Insufficient balance.',
    'Invalid document format.',
    'Invalid email address.',
    'Invalid verification code.',
    'Investment',
    'Investor password',
    'Jan',
    'January',
    'Jul',
    'July',
    'Jun',
    'June',
    'Jurisdiction',
    'Last Login',
    'Last Used',
    'Litecoin',
    'Lock Cashier',
    'Loss',
    'Low',
    'Low Barrier',
    'Low Tick',
    'Lower',
    'Lower or equal',
    'MAM Accounts',
    'MAM Advanced',
    'MAM Volatility Indices',
    'MT5 withdrawals have been disabled on your account. Please check your email for more details.',
    'Main password',
    'Manager successfully revoked',
    'Mar',
    'March',
    'Market is closed. Please try again later.',
    'Matches/Differs',
    'Maximum Payout',
    'Maximum Profit',
    'Maximum multiplier of 1000.',
    'Maximum payout',
    'May',
    'Minimum of [_1] characters required.',
    'Minute',
    'Minutes',
    'Mo',
    'Monday',
    'Month',
    'Months',
    'More information can be found in an email sent to you.',
    'Multiplier',
    'Name',
    'Net profit',
    'Network status',
    'Never',
    'Never Used',
    'New password',
    'New token created.',
    'Next',
    'Not',
    'Not announced for this currency.',
    'Note',
    'Note:',
    'Note: You are limited to one fiat currency account. The currency of your fiat account can be changed before you deposit into your fiat account for the first time or create an MT5 account. You may also open one account for each supported cryptocurrency.',
    'Nov',
    'November',
    'Now',
    'Oct',
    'October',
    'Offline',
    'Online',
    'Only Downs',
    'Only Ups',
    'Only Ups/Only Downs',
    'Only [_1] are allowed.',
    'Only letters, numbers, space, and hyphen are allowed.',
    'Only letters, numbers, space, and these special characters are allowed: [_1]',
    'Only letters, numbers, space, hyphen, period, and apostrophe are allowed.',
    'Only letters, numbers, space, underscore, and hyphen are allowed for ID number ([_1]).',
    'Only letters, space, hyphen, period, and apostrophe are allowed.',
    'Only numbers, hyphens, and spaces are allowed.',
    'Open a Financial Account',
    'Open a Real Account',
    'Opens',
    'Over/Under',
    'PM',
    'Passport',
    'Password is not strong enough.',
    'Password should have lower and uppercase letters with numbers.',
    'Payment Agent services are not available in your country or in your preferred currency.',
    'Payments',
    'Payout',
    'Payout Range',
    'Pending',
    'Percentage',
    'Permissions',
    'Please [_1]accept the updated Terms and Conditions[_2] to lift your deposit and trading limits.',
    'Please [_1]accept the updated Terms and Conditions[_2].',
    'Please [_1]complete your account profile[_2] to lift your withdrawal and trading limits.',
    'Please [_1]deposit[_2] to your account.',
    'Please [_1]log in[_2] or [_3]sign up[_4] to view this page.',
    'Please accept the terms and conditions.',
    'Please check your email for further instructions.',
    'Please check your email for the password reset link.',
    'Please choose a currency',
    'Please complete the [_1]Real Account form[_2] to verify your age as required by the [_3]UK Gambling[_4] Commission (UKGC).',
    'Please complete the [_1]financial assessment form[_2] to lift your withdrawal and trading limits.',
    'Please complete your [_1]personal details[_2] before you proceed.',
    'Please confirm that all the information above is true and complete.',
    'Please confirm that you are not a politically exposed person.',
    'Please ensure that you have the Telegram app installed on your device.',
    'Please enter a valid Login ID.',
    'Please log in.',
    'Please reapply once the required criteria has been fulfilled.',
    'Please reload the page',
    'Please select',
    'Please select a country',
    'Please select a valid time.',
    'Please select at least one scope',
    'Please select the checkbox.',
    'Please select the currency for this account:',
    'Please set [_1]country of residence[_2] before upgrading to a real-money account.',
    'Please set the [_1]currency[_2] of your account.',
    'Please set your [_1]30-day turnover limit[_2] to remove deposit limits.',
    'Postal Code/ZIP',
    'Potential Payout',
    'Potential Profit',
    'Potential Profit/Loss',
    'Predict the direction<br />and purchase',
    'Previous',
    'Profit',
    'Profit/Loss',
    'Purchase',
    'Purchase Price',
    'Purchase Time',
    'Purchase request sent',
    'Put Spread',
    'Read',
    'Real',
    'Real Account',
    'Real Advanced',
    'Real Standard',
    'Real Volatility Indices',
    'Real-Money Account',
    'Real-Money Accounts',
    'Ref.',
    'Reference ID',
    'Remaining Time',
    'Resale not offered',
    'Reset Barrier',
    'Reset Call',
    'Reset Password',
    'Reset Put',
    'Reset Time',
    'Return',
    'Reverse Side',
    'Revoke MAM',
    'Revoke access',
    'Rise/Fall',
    'Sa',
    'Sale Date',
    'Sale Price',
    'Saturday',
    'Scopes',
    'Search...',
    'Second',
    'Seconds',
    'Select Asset',
    'Select Trade Type',
    'Select date',
    'Select payment agent',
    'Select your market and underlying asset',
    'Select your trade type',
    'Selected Tick',
    'Sell',
    'Sell at market',
    'Sep',
    'September',
    'Session duration limit cannot be more than 6 weeks.',
    'Set Currency',
    'Settles',
    'Should be [_1]',
    'Should be a valid number.',
    'Should be between [_1] and [_2]',
    'Should be less than [_1]',
    'Should be more than [_1]',
    'Should start with letter or number, and may contain hyphen and underscore.',
    'Sign out',
    'Sign up',
    'Sorry, account signup is not available in your country.',
    'Sorry, an error occurred while processing your account.',
    'Sorry, an error occurred while processing your request.',
    'Sorry, this feature is available to virtual accounts only.',
    'Sorry, this feature is not available in your jurisdiction.',
    'Sorry, you have entered an incorrect cashier password',
    'Sorry, your account is not authorised for any further contract purchases.',
    'Spot',
    'Spot Time',
    'Spot Time (GMT)',
    'Stake',
    'Standard',
    'Start Time',
    'State/Province',
    'Status',
    'Stays Between',
    'Step',
    'Stocks',
    'Su',
    'Submitted',
    'Submitting',
    'Successful',
    'Sunday',
    'Target',
    'Telephone',
    'Tether',
    'Th',
    'Thank you for signing up! Please check your email to complete the registration process.',
    'Thank you, we\'ll get back to you within 24 hours',
    'The [_1] password of account number [_2] has been changed.',
    'The email address provided is already in use. If you forgot your password, please try our <a href="[_1]">password recovery tool</a> or contact our customer service.',
    'The maximum number of tokens ([_1]) has been reached.',
    'The password you entered is one of the world\'s most commonly used passwords. You should not be using this password.',
    'The reset time is [_1]',
    'The server <a href="[_1]">endpoint</a> is: [_2]',
    'The two passwords that you entered do not match.',
    'There was an error',
    'There was some invalid character in an input field.',
    'Therefore your current immediate maximum withdrawal (subject to your account having sufficient funds) is [_1] [_2] (or equivalent in other currency).',
    'Therefore your current immediate maximum withdrawal (subject to your account having sufficient funds) is [_1] [_2].',
    'This account is disabled',
    'This account is excluded until [_1]',
    'This contract lost',
    'This contract won',
    'This feature is not relevant to virtual-money accounts.',
    'This field is required.',
    'This is a staging server - For testing purposes only',
    'This is your [_1] account.',
    'This page is only available to logged out clients.',
    'This symbol is not active. Please try another symbol.',
    'Thursday',
    'Tick',
    'Ticks history returned an empty array.',
    'Time is in the wrong format.',
    'Time out cannot be in the past.',
    'Time out cannot be more than 6 weeks.',
    'Time out must be after today.',
    'Timed out until',
    'To account: ',
    'Today',
    'Token',
    'Top up error',
    'Top-up successful',
    'Total Cost',
    'Total Profit/Loss',
    'Touches',
    'Town/City',
    'Trade',
    'Trading Contracts for Difference (CFDs) on Volatility Indices may not be suitable for everyone. Please ensure that you fully understand the risks involved, including the possibility of losing all the funds in your MT5 account. Gambling can be addictive – please play responsibly.',
    'Trading and deposits have been disabled on your account. Kindly [_1]contact customer support[_2] for assistance.',
    'Trading is unavailable at this time.',
    'Transaction ID',
    'Transaction performed by [_1] (App ID: [_2])',
    'Try our [_1]Volatility Indices[_2].',
    'Try our other markets.',
    'Tu',
    'Tuesday',
    'Type',
    'Unable to read file [_1]',
    'Understood',
    'Unknown OS',
    'Unlock Cashier',
    'Up to [_1] decimal places are allowed.',
    'Up/Down',
    'Upcoming Events',
    'Update',
    'Upgrade now',
    'Verification code is wrong. Please use the link sent to your email.',
    'Verify Reset Password',
    'View',
    'View chart',
    'Virtual',
    'Volatility Indices',
    'Waiting for contract settlement.',
    'Waiting for entry tick.',
    'Waiting for exit tick.',
    'We',
    'We are reviewing your documents. For more details [_1]contact us[_2].',
    'Wednesday',
    'When you click "OK" you will be excluded from trading on the site until the selected date.',
    'Withdraw',
    'Withdrawals have been disabled on your account. Please check your email for more details.',
    'Yes',
    'Yes I\'m sure',
    'Yes, I\'m sure',
    'You are categorised as a professional client.',
    'You are categorised as a retail client. Apply to be treated as a professional trader.',
    'You are limited to one fiat account. You can change the currency of your fiat account anytime before you make a first-time deposit or create an MT5 account.',
    'You can [_1]set a new currency[_2] before you deposit for the first time or create an MT5 account.',
    'You can close this window without interrupting your trade.',
    'You can no longer change the currency because you\'ve created an MT5 account.',
    'You can no longer change the currency because you\'ve made a first-time deposit.',
    'You can top up your demo account with an additional [_1] if your balance is [_2] or less.',
    'You can top up your virtual account with an additional [_1] if your balance is [_2] or less.',
    'You did not change anything.',
    'You have already withdrawn [_1] [_2].',
    'You have already withdrawn the equivalent of [_1] [_2] in aggregate over the last [_3] days.',
    'You have already withdrawn the equivalent of [_1] [_2].',
    'You have insufficient funds in your Binary account, please <a href="[_1]">add funds</a>.',
    'You have not granted access to any applications.',
    'You have reached the limit.',
    'You have reached the rate limit of requests per second. Please try later.',
    'You have reached the withdrawal limit.',
    'You have sold this contract at [_1] [_2]',
    'You have successfully changed your account currency from [_1] to [_2].',
    'You have successfully disabled two-factor authentication for your account.',
    'You have successfully enabled two-factor authentication for your account.',
    'You may open one account for each supported cryptocurrency.',
    'You should enter [_1] characters.',
    'You will be redirected to a third-party website which is not owned by Binary.com.',
    'You will not be able to change your fiat account\'s currency after creating this MT5 account. Are you sure you want to proceed?',
    'You will not be able to change your fiat account\'s currency after making this deposit. Are you sure you want to proceed?',
    'Your [_1] day withdrawal limit is currently [_2] [_3] (or equivalent in other currency).',
    'Your account has no Login/Logout activity.',
    'Your account has no trading activity.',
    'Your account is fully authenticated and your withdrawal limits have been lifted.',
    'Your account is restricted. Kindly [_1]contact customer support[_2] for assistance.',
    'Your age verification failed. Please contact customer service for assistance. [_1][_1] [_2]Telephone:[_3] [_1] United Kingdom [_1] +44 (0) 1666 800042 [_1] 0800 011 9847 (Toll Free)',
    'Your application to be treated as a professional client is being processed.',
    'Your cashier is locked as per your request - to unlock it, please click <a href="[_1]">here</a>.',
    'Your cashier is locked as per your request - to unlock it, please enter the password.',
    'Your cashier is locked.',
    'Your changes have been updated successfully.',
    'Your changes have been updated.',
    'Your demo account balance is currently [_1] or less. You may top up your account with an additional [_2].',
    'Your fiat account\'s currency is currently set to [_1].',
    'Your fiat account\'s currency is set to [_1].',
    'Your password has been successfully reset. Please log into your account using your new password.',
    'Your professional client request is [_1]not approved[_2].',
    'Your request to transfer [_1] [_2] from [_3] to [_4] has been successfully processed.',
    'Your request to withdraw [_1] [_2] from your account [_3] to Payment Agent [_4] account has been successfully processed.',
    'Your session duration limit will end in [_1] seconds.',
    'Your settings have been updated successfully.',
    'Your token has expired or is invalid. Please click <a href="[_1]">here</a> to restart the verification process.',
    'Your token has expired or is invalid. Please click [_1]here[_2] to restart the verification process.',
    'Your trading statistics since [_1].',
    'Your transaction reference is',
    'Your transaction reference number is [_1]',
    'Your virtual account balance is currently [_1] or less. You may top up your account with an additional [_2].',
    'Your web browser ([_1]) is out of date and may affect your trading experience. Proceed at your own risk. [_2]Update browser[_3]',
    'Your withdrawal limit is [_1] [_2] (or equivalent in other currency).',
    'Your withdrawal limit is [_1] [_2].',
    '[_1] Account',
    '[_1] Account [_2]',
    '[_1] Please click the link below to restart the password recovery process.',
    '[_1] [_2] payout if [_3] does not touch Barrier through close on [_4].',
    '[_1] [_2] payout if [_3] ends on or between low and high values of Barrier at close on [_4].',
    '[_1] [_2] payout if [_3] ends outside low and high values of Barrier at close on [_4].',
    '[_1] [_2] payout if [_3] goes outside of low and high values of Barrier through close on [_4].',
    '[_1] [_2] payout if [_3] is strictly higher than or equal to Barrier at close on [_4].',
    '[_1] [_2] payout if [_3] is strictly lower than Barrier at close on [_4].',
    '[_1] [_2] payout if [_3] stays between low and high values of Barrier through close on [_4].',
    '[_1] [_2] payout if [_3] touches Barrier through close on [_4].',
    '[_1] and [_2] cannot be the same.',
    '[_1] days [_2] hours [_3] minutes',
    '[_1] deposit from [_2] to account number [_3] is done. Transaction ID: [_4]',
    '[_1] has been credited into your MT5 Demo Account: [_2].',
    '[_1] has been credited into your Virtual Account: [_2].',
    '[_1] requires your browser\'s web storage to be enabled in order to function properly. Please enable it or exit private browsing mode.',
    '[_1] withdrawal from account number [_2] to [_3] is done. Transaction ID: [_4]',
    '[_1]Authenticate your account[_2] now to take full advantage of all payment methods available.',
    '[_1]Manage your accounts[_2]',
    '[_1]No, change my fiat account\'s currency now[_2]',
    '[_1]Telephone numbers in other locations[_2]',
    '[_1]Your Proof of Identity or Proof of Address[_2] did not meet our requirements. Please check your email for further instructions.',
    'day',
    'days',
    'details',
    'for account [_1]',
    'h',
    'hour',
    'hours',
    'letters',
    'million',
    'minute',
    'minutes',
    'month',
    'months',
    'numbers',
    'second',
    'seconds',
    'space',
    'thousand',
    'tick',
    'ticks',
    'week',
    'weeks',
    'year',
    'years',
    '{SPAIN ONLY}However, Binary Investments (Europe) Ltd has assessed your knowledge and experience and deems the product appropriate for you.',
    '{SPAIN ONLY}This is a product with leverage. You should be aware that losses may be higher than the amount initially paid to purchase the product.',
    '{SPAIN ONLY}You are about to purchase a product that is not simple and may be difficult to understand: Contracts for Difference and Forex. As a general rule, the CNMV considers that such products are not appropriate for retail clients, due to their complexity.',
];
