import {
    isMultiplierContract,
    getFinalPrice,
    getIndicativePrice,
    getCancellationPrice,
    isEnded,
    isUserSold,
    isValidToCancel,
    isValidToSell,
    getCurrentTick,
    getLastTickFromTickStream,
    isDigitContract,
    getDigitInfo,
    getLimitOrderAmount,
    getTimePercentage,
    getDisplayStatus,
} from './contract';

export default {
    isMultiplierContract,
    getFinalPrice,
    getIndicativePrice,
    getCancellationPrice,
    isEnded,
    isUserSold,
    isValidToCancel,
    isValidToSell,
    getCurrentTick,
    getLastTickFromTickStream,
    isDigitContract,
    getDigitInfo,
    getLimitOrderAmount,
    getTimePercentage,
    getDisplayStatus,
};
