name: analyze
description: Analyze all packages
inputs:
  REF_NAME:
    description: 'Git ref name'
    required: true
    default: 'test'
  NODE_ENV:
    description: 'Node environment'
    required: false
    default: 'test'
  CROWDIN_WALLETS_API_KEY:
    description: 'Crowdin wallets api key'
    required: false
  DATADOG_CLIENT_TOKEN:
    description: 'Datadog client token'
    required: false
  DATADOG_APPLICATION_ID:
    description: 'Datadog application id'
    required: false
  DATADOG_CLIENT_TOKEN_LOGS:
    description: 'Datadog client token for logs'
    required: false
  DATADOG_SESSION_REPLAY_SAMPLE_RATE:
    description: 'Datadog session replay sample rate'
    required: false
  DATADOG_SESSION_SAMPLE_RATE:
    description: 'Datadog session sample rate'
    required: false
  GD_API_KEY:
    description: 'Google drive api key'
    required: false
  GD_APP_ID:
    description: 'Google drive app id'
    required: false
  GD_CLIENT_ID:
    description: 'Google drive client id'
    required: false
  RUDDERSTACK_KEY:
    description: 'Rudderstack key'
    required: false
  GROWTHBOOK_CLIENT_KEY:
    description: 'Growthbook key'
    required: false
  GROWTHBOOK_DECRYPTION_KEY:
    description: 'Growthbook decryption key'
    required: false
  DATADOG_SESSION_SAMPLE_RATE_LOGS:
    description: 'Datadog session sample rate for logs'
    required: false
  REMOTE_CONFIG_URL:
    description: 'Remote config backup URL'
    required: true
  IS_GROWTHBOOK_ENABLED:
    description: 'Is growthbook enabled'
    required: true

runs:
  using: composite
  steps:
  - name: Analyze all packages
    env:
      NODE_ENV: ${{ inputs.NODE_ENV }}
      CROWDIN_WALLETS_API_KEY: ${{ inputs.CROWDIN_WALLETS_API_KEY }}
      DATADOG_APPLICATION_ID: ${{ inputs.DATADOG_APPLICATION_ID }}
      DATADOG_CLIENT_TOKEN: ${{ inputs.DATADOG_CLIENT_TOKEN }}
      DATADOG_CLIENT_TOKEN_LOGS: ${{ inputs.DATADOG_CLIENT_TOKEN_LOGS }}
      DATADOG_SESSION_REPLAY_SAMPLE_RATE: ${{ inputs.DATADOG_SESSION_REPLAY_SAMPLE_RATE }}
      DATADOG_SESSION_SAMPLE_RATE: ${{ inputs.DATADOG_SESSION_SAMPLE_RATE }}
      DATADOG_SESSION_SAMPLE_RATE_LOGS: ${{ inputs.DATADOG_SESSION_SAMPLE_RATE_LOGS }}
      IS_GROWTHBOOK_ENABLED: ${{ inputs.IS_GROWTHBOOK_ENABLED }}
      GD_API_KEY: ${{ inputs.GD_API_KEY }}
      GD_APP_ID: ${{ inputs.GD_APP_ID }}
      GD_CLIENT_ID: ${{ inputs.GD_CLIENT_ID }}
      RUDDERSTACK_KEY: ${{ inputs.RUDDERSTACK_KEY }}
      GROWTHBOOK_CLIENT_KEY: ${{ inputs.GROWTHBOOK_CLIENT_KEY }}
      GROWTHBOOK_DECRYPTION_KEY: ${{ inputs.GROWTHBOOK_DECRYPTION_KEY }}
      REF_NAME: ${{ inputs.REF_NAME }}
      REMOTE_CONFIG_URL: ${{ inputs.REMOTE_CONFIG_URL }}
      NODE_OPTIONS: "--max_old_space_size=4096"
    run: npm run build:prod && npm run analyze:stats
    shell: bash

  - name: Zip all stats.json files
    run: |
      zip -r stats.zip packages/*/stats.json
    shell: bash

  - name: Upload stats.zip
    uses: actions/upload-artifact@v4
    with:
      name: stats-${{ github.sha }}
      path: stats.zip
      retention-days: 1
