import React from 'react';

const ConflictsPolicy = () => (
    <div>
        <h2 data-anchor='conflicts-policy'>{it.L('Summary of the Conflicts policy')}</h2>
        <p>{it.L('The Company provides here a summary of the policy that the Company maintains in order to manage conflicts of interest in respect of the duties that the Company owes to clients.')}</p>

        <h2 data-anchor='general'>{it.L('General')}</h2>
        <p>{it.L('Due to the nature of the Company\'s business as a trading counterparty, the Company\'s profits are tied to the net revenue generated by clients through trading. However, the Company aims to establish, maintain, and operate effective organisational and administrative arrangements with a view to taking all reasonable steps to prevent conflicts of interest from constituting or giving rise to a material risk of damage to the interests of clients.')}</p>
        <p>{it.L('Due to the high degree of risk involved, which could result in the loss of the entire investment, the Company has adequate internal procedures in place to ensure that the client is in all cases treated fairly and that the risk of damage to client interests will be mitigated.')}</p>

        <h2 data-anchor='our-policy'>{it.L('The Company\'s policy')}</h2>
        <p>{it.L('The Company aims to keep a record of the kinds of activity that the Company carries on in which a material conflict could arise or has arisen. The Company also maintains procedures to manage actual or potential conflicts. This includes procedures to maintain appropriate independence among members of the Company\'s staff who are involved in potentially conflicting activities. Such independence-upholding procedures can be followed, for example, through the operation of information barriers, physical separation of staff, the segregation of duties and responsibilities, and the maintenance of a policy of independence, which requires the Company\'s staff, when providing services to a client, to act in the best interests of the client and to disregard any conflicts of interest, or in some circumstances, to decline to act for a client or potential client in order to avoid conflicts of interest.')}</p>

        <h2 data-anchor='disclosure-general'>{it.L('Disclosure: general')}</h2>
        <p>{it.L('The organisational and administrative arrangements established by the Company to prevent or manage the conflict are not sufficient to ensure, with reasonable confidence, that the risk of damage to the interest of the client will be prevented. However, the Company aims to disclose the general nature or sources of conflicts of interest.')}</p>
        <p data-show='eucountry'>{it.L('Clients have the opportunity to consider whether to ask for more information by sending an email to compliance@binary.com, in which case further details of the conflicts of interest policy will be made available.')}</p>
    </div>
);

export default ConflictsPolicy;
