const mock_wallet_migration_response = [
    {
        title: 'Non-EU USD accounts',
        currency: 'USD',
        landing_company_name: 'svg',
        account_list: [
            {
                loginid: 'CR007',
                account_category: 'trading',
                account_type: 'standart',
                platform: 'dtrade',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                balance: '7.00',
                currency: 'USD',
                account_name: 'MT5 Derived SVG',
                icon: 'IcRebrandingMt5Logo',
            },
            {
                loginid: 'MTR234',
                account_category: 'trading',
                account_type: 'mt5',
                platform: 'mt5',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                sub_account_category: 'stp',
                balance: '123.00',
                currency: 'USD',
                account_name: 'MT5 Derived BVI',
                icon: 'IcRebrandingMt5Logo',
            },
        ],
    },
    {
        title: 'EU-regulated USD accounts',
        currency: 'USD',
        landing_company_name: 'malta',
        account_list: [
            {
                loginid: 'CR123',
                account_category: 'trading',
                account_type: 'standart',
                platform: 'dtrade',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                balance: '123.00',
                currency: 'USD',
                account_name: 'MT5 Financial SVG',
                icon: 'IcRebrandingMt5Logo',
            },
            {
                loginid: 'MTR234',
                account_category: 'trading',
                account_type: 'mt5',
                platform: 'mt5',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                sub_account_category: 'stp',
                balance: '234.00',
                currency: 'USD',
                account_name: 'MT5 Derived Vanuata',
                icon: 'IcRebrandingMt5Logo',
            },
        ],
    },
    {
        title: 'Cryptocurrency accounts',
        account_list: [
            {
                loginid: 'CR567',
                account_category: 'trading',
                account_type: 'Bitcoin',
                platform: 'dtrade',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                balance: '567.00',
                currency: 'BTC',
                account_name: 'Bitcoin',
                icon: 'IcCurrencyBtc',
            },
            {
                loginid: 'CR89',
                account_category: 'trading',
                account_type: 'Ethereum',
                platform: 'dtrade',
                landing_company_name: 'svg',
                sub_account_type: 'financial',
                balance: '89.00',
                currency: 'ETH',
                account_name: 'Ethereum',
                icon: 'IcCurrencyEth',
            },
        ],
    },
];

export default mock_wallet_migration_response;
