// TODO: Remove this file once we have the real API response
const wallets = [
    {
        name: 'USD Wallet',
        currency: 'usd',
        icon: 'IcCurrencyUsd',
        balance: '10,0000',
        icon_type: 'fiat',
        state: 'default',
        jurisdiction_title: 'svg',
    },
    {
        name: 'USD Wallet',
        currency: 'usd',
        icon: 'IcCurrencyUsd',
        balance: '10,0000',
        icon_type: 'fiat',
        state: 'default',
        jurisdiction_title: 'svg',
    },
    // {
    //     name: 'MT5 Derived Demo',
    //     currency: 'usd',
    //     icon: 'IcRebrandingMt5Logo',
    //     wallet_icon: 'IcWalletDerivDemoLight',
    //     balance: '879',
    //     icon_type: 'app',
    //     app: 'mt5',
    //     linked_wallet: 'deriv demo',
    //     state: 'default',
    //     jurisdiction_title: 'svg',
    //     is_demo: true,
    // },
    // {
    //     name: 'MT5 Derived Demo',
    //     currency: 'usd',
    //     icon: 'IcRebrandingMt5Logo',
    //     wallet_icon: null,
    //     balance: '879',
    //     icon_type: 'app',
    //     app: 'mt5',
    //     linked_wallet: null,
    //     state: 'default',
    //     jurisdiction_title: 'svg',
    //     is_demo: true,
    // },
    {
        name: 'Bitcoin Wallet',
        currency: 'BTC',
        icon: 'IcCashierBitcoinLight',
        balance: '0.003546',
        icon_type: 'crypto',
        state: 'default',
        jurisdiction_title: 'svg',
    },
];

export default wallets;
