export const IconTradeTypesMap = {
    asiand      : '',
    asianu      : '',
    call        : 'IconTradetypesRise',
    calle       : 'IconTradetypesRise',
    callspread  : '',
    call_barrier: 'IconTradetypesHigher',
    calle_light : '',
    digitdiff   : 'IconTradetypesDigitdiff',
    digiteven   : 'IconTradetypesDigiteven',
    digitmatch  : 'IconTradetypesDigitmatch',
    digitodd    : 'IconTradetypesDigitodd',
    digitover   : 'IconTradetypesDigitover',
    digitunder  : 'IconTradetypesDigitunder',
    expirymiss  : '',
    expiryrange : '',
    expiryrangee: '',
    lbfloatcall : '',
    lbfloatput  : '',
    lbhighlow   : '',
    notouch     : 'IconTradetypesNoTouch',
    onetouch    : 'IconTradetypesTouch',
    put         : 'IconTradetypesFall',
    pute        : 'IconTradetypesFall',
    putspread   : '',
    put_barrier : 'IconTradetypesLower',
    resetcall   : '',
    resetput    : '',
    runhigh     : '',
    runlow      : '',
    tickhigh    : '',
    ticklow     : '',
    upordown    : '',
};
