name: npm_install
description: Install npm packages
runs:
  using: composite
  steps:
  - name: Install npm packages
    run: npm ci
    shell: bash
  - name: Bootstrap 
    run: npm run bootstrap:ci
    shell: bash
