import { popover_zindex } from 'Constants/z-indexes';

const data_fields = [
    {
        num: 0,
        id: 'firstName',
        name: 'firstName',
        label: '',
        field_name: 'quick-strategy__types-strategies',
        dropdown_item: 'type-strategy',
        className: '',
        isAbleBeDisabled: 'true',
        isDouble: true,
    },
    {
        id: 'martingale__stake',
        name: 'martingale__stake',
        field_name: 'quick-strategy__stake',
        className: 'quick-strategy__input',
        label_className: 'quick-strategy__input-label',
        field_className: 'quick-strategy__input-field',
        input_value: 'input_stake',
        label: 'Initial stake',
        placeholder: '10',
        trailing_icon_message: 'The amount that you pay to enter a trade.',
        zIndex: popover_zindex.QUICK_STRATEGY,
    },
    {
        id: 'martingale__loss',
        name: 'martingale__loss',
        field_name: 'quick-strategy__loss',
        className: 'quick-strategy__input',
        label_className: 'quick-strategy__input-label',
        field_className: 'quick-strategy__input-field',
        input_value: 'input_loss',
        label: 'Loss threshold',
        placeholder: '5000',
        trailing_icon_message: 'The bot will stop trading if your total loss exceeds this amount.',
        zIndex: popover_zindex.QUICK_STRATEGY,
    },
    {
        id: 'martingale__profit',
        name: 'martingale__profit',
        field_name: 'quick-strategy__profit',
        className: 'quick-strategy__input',
        label_className: 'quick-strategy__input-label',
        field_className: 'quick-strategy__input-field',
        input_value: 'input_profit',
        label: 'Profit threshold',
        placeholder: '5000',
        trailing_icon_message: 'The bot will stop trading if your total profit exceeds this amount.',
        zIndex: popover_zindex.QUICK_STRATEGY,
    },
];
export default data_fields;
