name: publish_to_pages_uat
description: Publish to cloudflare pages (UAT)
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account id'
    required: true
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare token'
    required: true
  BRANCH_NAME:
    description: 'Branch name'
    required: true
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (UAT)
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
    run: |
      npm i wrangler@3.1.0
      cd packages/core
      npx wrangler pages deploy dist/ --project-name=deriv-app-pages --branch=${{ inputs.BRANCH_NAME }}
      echo "New uat website - https://${{ inputs.BRANCH_NAME }}.cf-pages-deriv-app.deriv.com"
    shell: bash
