import React from 'react';
import { localize } from '@deriv/translations';

const Article = () => (
    <article className='two-factor__article'>
        <h4 className='two-factor__article-title'>{localize('Two-factor authentication (2FA)')}</h4>
        <ul className='two-factor__article-list'>
            <li>
                <p className='two-factor__article-text'>
                    {localize(
                        'Protect your account with 2FA. Each time you log in to your account, you will need to enter your password and an authentication code generated by a 2FA app on your smartphone.'
                    )}
                </p>
            </li>
        </ul>
    </article>
);

export default Article;
