import React from 'react';
import { Icon, ThemedScrollbars, Text } from '@deriv/components';
import { isMobile } from '@deriv/shared';
import { localize } from '@deriv/translations';
import DigitForm from './digit-form';

type TTwoFactorEnabled = {
    setTwoFAStatus: (status: boolean) => void;
};

const TwoFactorEnabled = ({ setTwoFAStatus }: TTwoFactorEnabled) => {
    return (
        <ThemedScrollbars is_bypassed={isMobile()} className='two-factor__scrollbars'>
            <div className='two-factor__wrapper--enabled'>
                <Icon icon='IcQrPhone' className='two-factor__icon' />
                <Text as='h3' align='center' weight='bold' color='prominent' className='two-factor__qr--title'>
                    {localize('2FA enabled')}
                </Text>
                <Text as='h4' size='xs' align='center' className='two-factor__qr--message'>
                    {localize('You have enabled 2FA for your Deriv account.')}
                </Text>
                <Text as='h4' size='xs' align='center' className='two-factor__qr--message'>
                    {localize(
                        'To disable 2FA, please enter the six-digit authentication code generated by your 2FA app below:'
                    )}
                </Text>
                <div data-testid='digitform_2fa_enabled'>
                    <DigitForm setTwoFAStatus={setTwoFAStatus} />
                </div>
            </div>
        </ThemedScrollbars>
    );
};

export default TwoFactorEnabled;
