import React from 'react';
import Loading from '../../../_common/components/loading.jsx';

const ErrorMessage = ({ id }) => (
    <React.Fragment>
        <p className='invisible notice-msg center-text' id={id} />
    </React.Fragment>
);

const OtpForm = () => (
    <React.Fragment>
        <form id='frm_two_factor_auth' className='invisible'>
            <div className='otp-form-group'>
                <div>
                    <input type='text' id='otp' placeholder={it.L('6-digit code')} maxLength='6' />
                    <button type='submit' id='btn_submit' />
                </div>
            </div>
            <p id='frm_two_factor_auth_error' className='error-msg' />
            <p id='frm_two_factor_auth_success' className='success-msg' />
        </form>
    </React.Fragment>
);

const TwoFactorStatus = ({ type }) => (
    <div className='two-fa-status'>
        <div className='two-fa-status-container'>
            <img className='responsive two-fa-status-icon' src={it.url_for(`images/pages/settings/2fa-${type}.svg`)} />
            <p className='two-fa-status-text'>{it.L(`Two-factor authentication is currently ${type}.`)}</p>
        </div>
    </div>
);

const TwoFactorAuthentication = () => (
    <React.Fragment>
        <div className='two_factor_auth'>
            <h1>{it.L('Two-Factor Authentication')}</h1>
            <p>{it.L('Protect your account with two-factor authentication. Each time you sign into your account, you will need to enter your password, plus an authentication code generated by an app on your smartphone.')}</p>

            <div id='two_factor_loading'><Loading /></div>
            <ErrorMessage id='status_error' />

            <div id='disabled' className='invisible'>
                <TwoFactorStatus type='disabled' />

                <h2>{it.L('How to setup two-factor authentication for your [_1] account:', it.website_name)}</h2>

                <div className='steps steps-vertical'>
                    <div className='step'>
                        <div className='circle'>1</div>
                        <div className='content'>
                            <p>{it.L('Scan the QR code below with your authentication app. We recommend [_1] or [_2]. Please note that [_3] is not supported.', '<a href="https://authy.com" target="_blank" rel="noopener noreferrer">Authy</a>', '<a href="https://github.com/google/google-authenticator/wiki#implementations" target="_blank" rel="noopener noreferrer">Google Authenticator</a>', '<a href="https://help.duo.com/s/article/2112?language=en_US" target="_blank" rel="noopener noreferrer">Duo Mobile</a>')}</p>
                            <div id='qrcode_loading'><Loading /></div>
                            <ErrorMessage id='generate_error' />
                            <div id='qrcode' />
                            <p>{it.L('If you are unable to scan the QR code, you can manually enter this code instead:')}<br /><strong><span id='qrcode_key' /></strong></p>
                        </div>
                    </div>
                    <div className='step'>
                        <div className='circle'>2</div>
                        <div className='content'>
                            <p>{it.L('Enter the authentication code generated by the app below:')}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div id='enabled' className='invisible'>
                <TwoFactorStatus type='enabled' />
                <p>{it.L('To disable two-factor authentication, please enter the code generated by the app below:')}</p>
            </div>

            <OtpForm />
        </div>
    </React.Fragment>
);

export default TwoFactorAuthentication;
