export const V2_QS_STRATEGIES = [
    'ACCUMULATORS_MARTINGALE',
    'ACCUMULATORS_DALEMBERT',
    'ACCUMULATORS_MARTINGALE_ON_STAT_RESET',
    'ACCUMULATORS_DALEMBERT_ON_STAT_RESET',
    'ACCUMULATORS_REVERSE_MARTINGALE',
    'ACCUMULATORS_REVERSE_MARTINGALE_ON_STAT_RESET',
    'ACCUMULATORS_REVERSE_DALEMBERT',
];
