export const V2_QS_STRATEGIES = [
    'ACCUMULATORS_MARTINGALE_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_DALEMBERT_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_MARTINGALE_ON_STAT_RESET_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_DALEMBERT_ON_STAT_RESET_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_REVERSE_MARTINGALE_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_REVERSE_MARTINGALE_ON_STAT_RESET_WITH_TICK_COUNT_TAKE_PROFIT',
    'ACCUMULATORS_REVERSE_DALEMBERT_WITH_TICK_COUNT_TAKE_PROFIT',
];
