import {
    getDerivComLink,
    reset,
    params,
    paramsHash,
    normalizePath,
    urlFor,
    urlForCurrentDomain,
    urlForLanguage,
    urlForStatic,
    websiteUrl,
    getUrlBase,
    removeBranchName,
    param,
    getHostMap,
    resetStaticHost,
    setUrlLanguage,
} from './url';

export default {
    getDerivComLink,
    reset,
    params,
    paramsHash,
    normalizePath,
    urlFor,
    urlForCurrentDomain,
    urlForLanguage,
    urlForStatic,
    websiteUrl,
    getUrlBase,
    removeBranchName,
    param,
    getHostMap,
    resetStaticHost,
    setUrlLanguage,
};
