import React from 'react';
import { DerivLightQrPhoneSuccessIcon } from '@deriv/quill-icons';
import { Text } from '@deriv-com/ui';
import { TwoFactorAuthenticationForm } from '../../containers/TwoFactorAuthenticationForm';

export const TwoFactorAuthenticationEnabled = () => {
    return (
        <div className='flex flex-1 flex-col items-center w-full h-full'>
            <div className='w-[83px] h-[123px] mt-[64px]'>
                <DerivLightQrPhoneSuccessIcon />
            </div>
            <Text
                align='center'
                as='h3'
                className='mt-[24px] text-[16px] leading-normal'
                color='prominent'
                weight='bold'
            >
                2FA enabled
            </Text>
            <Text align='center' as='h4' className='mt-[16px] mb-0 mx-0 text-[14px] leading-normal' color='general'>
                You have enabled 2FA for your Deriv account.
            </Text>
            <Text align='center' as='h4' className='mt-[16px] mb-0 mx-0 text-[14px] leading-normal' weight='normal'>
                To disable 2FA, please enter the six-digit authentication code generated by your 2FA app below:
            </Text>
            <TwoFactorAuthenticationForm />
        </div>
    );
};
