import React from 'react';
import classNames from 'classnames';
import { twMerge } from 'tailwind-merge';
import { SideNote, Text, useDevice } from '@deriv-com/ui';

/* TODO: Remember to size the SideNote component to the same width as v1 */
export const TwoFactorAuthenticationArticle = () => {
    const { isTablet } = useDevice();
    return (
        <SideNote
            className={twMerge(
                // classNames('py-[1.6rem] px-[2.4rem] h-fit w-[25.6rem]', {
                //     'ml-[1.2rem]': isTablet,
                //     'w-[calc(100%-3.2rem)] m-[1.6rem]': isMobile,
                // })
                classNames('py-[1.6rem] px-[2.4rem] h-fit w-[25.6rem] sm:w-[calc(100%-3.2rem)] sm:m-[1.6rem]', {
                    'ml-[1.2rem]': isTablet,
                })
            )}
        >
            {/* TODO: Title prop has different styles. Will talk to the ui team to fix it */}
            <Text
                as='h4'
                className='mb-[.8rem] text-[1.4rem] text-system-light-prominent-text leading-normal'
                weight='bold'
            >
                Two-factor authentication (2FA)
            </Text>
            <Text align='start' className='text-[1.2rem] text-system-light-prominent-text leading-normal'>
                Protect your account with 2FA. Each time you log in to your account, you will need to enter your
                password and an authentication code generated by a 2FA app on your smartphone.
            </Text>
        </SideNote>
    );
};
