import React, { ComponentProps, useEffect } from 'react';
import { useAuthorize, useTwoFactorAuthentication } from '@deriv/api-v2';
import { Loader, Text } from '@deriv-com/ui';
import { Timeline } from '../../components/Timeline';
import { TwoFactorAuthenticationForm } from '../../containers/TwoFactorAuthenticationForm';
import { TwoFactorAuthenticationArticle } from './TwoFactorAuthenticationArticle';
import { TwoFactorAuthenticationQRCode } from './TwoFactorAuthenticationQRCode';

const TwoFactorAuthenticationLink = ({
    children,
    className = 'hover:underline font-bold',
    ...rest
}: ComponentProps<'a'>) => {
    return (
        <a {...rest} className={className} rel='noopener noreferrer' target='_blank'>
            {children}
        </a>
    );
};

export const TwoFactorAuthenticationDisabled = () => {
    const { data: authorizeData } = useAuthorize();
    const { email = '' } = authorizeData ?? {};
    const { data: secretKeyData, isLoading, mutate } = useTwoFactorAuthentication();
    const { secretKey } = secretKeyData ?? {};
    useEffect(() => {
        mutate({ totp_action: 'generate' });
    }, [mutate]);

    return (
        <div className='flex flex-1 w-full h-full sm:flex-col-reverse'>
            <section className='py-0 px-[1.4rem]'>
                <Text
                    align='start'
                    as='h2'
                    className='ml-[1.2rem] mb-[1.5rem] text-[1.6rem] text-system-light-prominent-text leading-normal sm:mr-1.2rem'
                    weight='bold'
                >
                    How to set up 2FA for your Deriv account
                </Text>
                <Timeline className='pt-0 px-[1.4rem] pb-[1.6rem] m-[1.2rem] w-full' lineHeight='xs'>
                    <Timeline.Item
                        itemTitle={
                            <Text
                                align='start'
                                className='leading-tight text-[1.4rem] text-system-light-prominent-text'
                            >
                                Scan the QR code below with your 2FA app. We recommend{' '}
                                <TwoFactorAuthenticationLink
                                    aria-label='Authy' // TODO: Remember to localize this
                                    href='https://authy.com/'
                                >
                                    Authy
                                </TwoFactorAuthenticationLink>{' '}
                                or{' '}
                                <TwoFactorAuthenticationLink
                                    aria-label='Google Authenticator' // TODO: Remember to localize this
                                    href='https://github.com/google/google-authenticator/wiki#implementations'
                                >
                                    Google Authenticator
                                </TwoFactorAuthenticationLink>
                                .
                            </Text>
                        }
                    >
                        <div className='flex flex-col items-center mb-[1.6rem]'>
                            {isLoading ? (
                                <Loader isFullScreen={false} />
                            ) : (
                                <TwoFactorAuthenticationQRCode emailAddress={email} secretKey={secretKey} />
                            )}
                        </div>
                    </Timeline.Item>
                    <Timeline.Item
                        itemTitle={
                            <Text
                                align='start'
                                className='m-w-[500px] text-[1.4rem] leading-tight text-system-light-prominent-text'
                            >
                                Enter the authentication code generated by your 2FA app:
                            </Text>
                        }
                    >
                        <TwoFactorAuthenticationForm />
                    </Timeline.Item>
                </Timeline>
            </section>
            <TwoFactorAuthenticationArticle />
        </div>
    );
};
