import React from 'react';
import classNames from 'classnames';
import { SideNote, Text, useDevice } from '@deriv-com/ui';

export const TwoFactorAuthenticationArticle = () => {
    const { isTablet } = useDevice();
    return (
        <SideNote
            className={classNames('py-[16px] px-[24px] h-fit w-[256px] sm:w-[calc(100%-32px)] sm:m-[16px]', {
                'ml-[12px]': isTablet,
            })}
            title='Two-factor authentication (2FA)'
            titleClassName='mb-[8px] text-[14px] text-system-light-prominent-text leading-normal'
        >
            <Text align='start' className='text-[12px] text-system-light-prominent-text leading-normal'>
                Protect your account with 2FA. Each time you log in to your account, you will need to enter your
                password and an authentication code generated by a 2FA app on your smartphone.
            </Text>
        </SideNote>
    );
};
