const containers = {
    account_transfer: 'account_transfer',
    deposit: 'deposit',
    payment_agent: 'payment_agent',
    payment_agent_transfer: 'payment_agent_transfer',
    withdraw: 'withdraw',
};

const map_action = {
    withdraw: 'payment_withdraw',
    payment_agent: 'payment_agent_withdraw',
};

const icon_payment_methods = {
    Alipay: ['alipay'],
    Bank: [
        'bank',
        'bankdeposit',
        'banks',
        'banktransfer',
        'bankwire',
        'bankwiretransfer',
        'localbankwire',
        'localbank',
        'localbanks',
        'localbanktransfer',
    ],
    Bankbri: ['bri', 'bankbri'],
    Bca: ['bca', 'grupbca'],
    Bch: ['bch'],
    Bni: ['bni'],
    Bitcoin: ['bitcoin', 'btc'],
    Card: ['card', 'cards', 'visa', 'mastercard'],
    Cimbniaga: ['cimbniaga'],
    Crypto: ['crypto', 'cryptos', 'cryptocurrencies', 'cryptocurrency', 'weacceptcrypto'],
    Dai: ['dai'],
    Diamondbank: ['diamondbank'],
    Eth: ['eth', 'ethd', 'ethereum'],
    Ewallet: ['ewallet', 'ewallets', 'ewalletpayment', 'skrill'],
    Firstbank: ['firstbank'],
    Gtbank: ['gtbank'],
    Icbc: ['icbc'],
    Libertyreserve: ['libertyreserve'],
    LiteCoin: ['ltc', 'litecoin'],
    Mandiri: ['mandiri'],
    Mandirisyariah: ['mandirisyariah'],
    Moneygram: ['moneygram'],
    Paypal: ['paypal'],
    PerfectMoney: ['perfectmoney'],
    Permatabank: ['permatabank'],
    Tether: ['tether'],
    Verve: ['verve'],
    Wechatpay: ['wechatpay'],
    Zenithbank: ['zenithbank'],
};

const payment_methods = {
    'ABSA Bank': [
        'Absa',
        'ABSA',
        'ABSA Bank',
        'ABSABank',
        'ABSABANK',
        'ABSA Bank Transfer',
        'ABSA Cash Send',
        'Absa fund transfer and orange money services',
        'ABSA GHANA LIMITED',
        'Cashsend',
        'Cash Send',
        'CashSend',
        'cash send Absa',
        'Cash send Absa bank',
        'Direct deposit FNB and ABSA',
    ],
    'Access Bank': ['Access bank', 'Access Bank', 'AccessBank', 'ACCESS BANK', 'Acess Bank'],
    'Access Forex': ['Access forex', 'Access Forex', 'ACCESS FOREX'],
    'Afriland First Bank': ['Afriland First Bank', 'AFRILAND FIRST BANK'],
    Airtel: [
        'airtel',
        'Airtel',
        'AIRTEL MOBILE MONEY',
        'airtel money',
        'Airtel money',
        'Airtelmoney',
        'Airtel Money',
        'AirtelMoney',
        'AIRTEL MONEY',
        'Airtel Tigo',
    ],
    Airtm: ['airtm', 'Airtm'],
    AstroPay: ['astropay', 'Astropay', 'Astro Pay'],
    ATM: ['ATM', 'ATMDeposits', 'ATM transfer', 'ATM Transfer', 'BanktransferATM'],
    'Bank Alfalah': ['AlfalahBank', 'bank alfalfa'],
    'Bank BRI': ['BankBri', 'BankBRI', 'BRI'],
    'Bank (Wire, Transfer, Deposit)': [
        'All Local Bank payment Accept',
        'All local bank payments',
        'All local banks',
        'All local Banks',
        'All local banks ZWL',
        'All Local Bank transfer',
        'bank',
        'Bank',
        'BANK',
        'Bank and E-wallet',
        'bank deposit',
        'Bank deposit',
        'Bankdeposit',
        'Bank Deposit',
        'Bank deposits',
        'bank ewallet',
        'bank payment',
        'banks',
        'Banks',
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'Bank to Bank account transfer',
        'bank transfer',
        'Bank transfer',
        'Banktransfer',
        'Bank Transfer',
        'BankTransfer',
        'BANK TRANSFER',
        'BANKTRANSFER',
        'bank transfer and all form of E-payments',
        'Bank Transfer and all Forms of E-payments',
        'BanktransferATM',
        'bank transfers',
        'Bank transfers',
        'Bank Transfers',
        'bank wire',
        'bankwire',
        'Bank wire',
        'Bankwire',
        'Bank Wire',
        'BankWire',
        'BANKWIRE',
        'Bank wire and e-wallets',
        'Bank wire and E-wallets',
        'Bank wires',
        'Bankwires',
        'bank wires and e-wallet',
        'Bank wires and e-wallets',
        'BankWire transfer',
        'Ban transfer',
        'E-wallet Bank transfer',
        'E-wallets and bank wires',
        'FNBB Bank Transfer',
        'LocalBank',
        'local banks',
        'Local banks',
        'Local Banks',
        'Local bank transfer',
        'Local bank Transfers',
        'local bank wire',
        'LocalBankWire',
        'Local deposits',
        'Nigeria Local',
        'Nigeria local bank',
        'NIGERIA LOCAL BANK',
        'Or USSD transfer from all Nigeria banks',
        'Pakistani Local All banks',
        'physical local and foreign bank notes',
        'Wire Bank Transfer',
        'WIRE TRANSFER',
    ],
    'BCA Group': ['BCA', 'GrupBCA'],
    BHIMUP: ['Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe'],
    BTC: [
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'bitcoin',
        'Bitcoin',
        'BITCOIN',
        'bitcoins',
        'Bitcoins',
        'btc',
        'BTC',
    ],
    'CABS Bank': ['Cabs bank', 'CABS transfer'],
    Card: ['card', 'Card', 'cards', 'Cards', 'Credit card', 'Debit Card'],
    Cash: [
        'cash',
        'Cash',
        'Cash deposit',
        'Cash deposits',
        'Cash in USD or Local',
        'electronic transfers and cash deposits',
        'FNB cash deposit',
    ],
    'Chipper Cash': ['Chipper', 'Chippercash'],
    'CIMB Niaga': ['CIMB', 'CIMBNIAGA'],
    'Conta Movel': ['Conta movel', 'Conta Movel', 'ContamovelBCI'],
    Cryptocurrency: [
        'Cripto',
        'crypto',
        'Crypto',
        'cryptocurrencies',
        'Cryptocurrencies',
        'Crypto Currencies',
        'CRYPTOCURRENCIES',
        'cryptocurrency',
        'Cryptocurrency',
        'CRYPTOCURRENCY',
        'Cryptos',
        'We accept Crypto',
    ],
    'Diamond Bank': ['Diamond bank', 'Diamond Bank', 'DiamondBank'],
    'e-Mola': ['E-mola', 'Emola'],
    'E-payments': [
        'all form of E-payments',
        'All form of E-payments',
        'all forms of E-payments',
        'and all other forms of Epayment',
        'bank transfer and all form of E-payments',
        'Bank Transfer and all Forms of E-payments',
        'E-payments',
        'Epayments',
    ],
    'E-wallet': [
        'Bank and E-wallet',
        'bank ewallet',
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'Bank wire and e-wallets',
        'Bank wire and E-wallets',
        'bank wires and e-wallet',
        'Bank wires and e-wallets',
        'electronic wallets',
        'e-wallers',
        'e-wallet',
        'ewallet',
        'eWallet',
        'E-wallet',
        'Ewallet',
        'EWALLET',
        'E-wallet Bank transfer',
        'E wallet FNB',
        'E-wallet payment',
        'Ewallet payment',
        'e-wallets',
        'ewallets',
        'e-Wallets',
        'e-WALLETS',
        'E- wallets',
        'E-wallets',
        'Ewallets',
        'E-Wallets',
        'E-wallets and bank wires',
        'fnb ewallet',
    ],
    Easypaisa: ['easypaisa', 'Easy paisa', 'Easypaisa', 'Easy Paisa', 'EasyPaisaTransfer'],
    Ecobank: ['Ecobank', 'Eco Bank', 'ECO BANK', 'Eco bank Transfers'],
    EcoCash: [
        'Eco cash',
        'Ecocash',
        'EcoCash',
        'ECOCASH',
        'Ecocash',
        'Ecocash method',
        'ECOCASH WALLET',
        'Ecocash ZWL',
    ],
    'E-transfers': ['electronic transfers and cash deposits', 'E-Transfers'],
    'Equity Bank': ['Equity bank', 'Equity Bank'],
    eUSDT: ['eUSDT', 'EUSDT'],
    Ezypesa: ['Ezypesa', 'Ezzy pesa', 'Ezzy Pesa', 'Ezzy Pesa', 'EzzyPesa'],
    FasaPay: ['fasapay', 'Fasa pay'],
    FCMB: ['FCMB', 'fcmb'],
    FinBank: ['Fin bank', 'FinBank'],
    'First Bank': ['First bank', 'First Bank', 'FirstBank', 'FIRST BANK'],
    'First National Bank (FNB)': [
        'Direct deposit FNB and ABSA',
        'E wallet FNB',
        'fnb',
        'FNB',
        'Fnbbank',
        'FNB Bank',
        'FNBB Bank Transfer',
        'FNB cash deposit',
        'fnb ewallet',
        'First National Bank',
        'FNB First National Bank',
        'FNB pay2cell',
        'FNB pay to cell',
        'FNB pay to sell',
        'Pay to cell FNB',
    ],
    GMONEY: ['Gmoney', 'GMONEY'],
    'Google Pay': [
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'Google pay',
        'gpay',
        'Gpay',
    ],
    GTBank: ['Gtb', 'GTB', 'Gt Bank', 'GT Bank', 'GTBank', 'GT BANK'],
    Halopesa: ['halopesa', 'Halo pesa', 'Halopesa', 'Halo Pesa', 'HaloPesa', 'HALOPESA'],
    IMPS: ['imps', 'Imps', 'IMPS', 'IMPS Transfer'],
    InnBucks: ['Innbucks', 'INNBUCKS'],
    'Instant Money Stanbic': ['InstantMoney', 'Instant money stambic bank', 'Instant money stanbic'],
    InterBank: ['InterBankfundtransfer', 'Interbank Transfer'],
    'Internet Transfer': ['Internet transfer', 'Internet Transfer'],
    JazzCash: ['jazzcash', 'Jazz cash', 'Jazzcash', 'Jazz-Cash', 'JazzCashTransfer'],
    Jeton: ['Jeton', 'jeton'],
    'Kuda Bank': ['Kuda Bank', 'KUDA BANK', 'Kuda MFB', 'KudaMFB', 'KUDA MICROFINANCE BANK 2014563937'],
    Luno: ['Luno', 'Luno crypto wallet'],
    Mandiri: ['Mandiri', 'MANDIRI'],
    'Mascom MyZaka': [
        'mascom myZaka',
        'Mascom MyZaka',
        'myzaka',
        'My zaka',
        'Myzaka',
        'MyZaka',
        'My zaka mascom money',
    ],
    Mastercard: ['Mastercard', 'MasterCard'],
    'Meezan Bank': ['Meezan Bank', 'MeezanBank'],
    'Millenium bim': ['Bim', 'Millenium Bim Visa'],
    Mixed: ['mix', 'Mix', 'MIX', 'Mixed'],
    'Mobile Banking': ['mobile banking', 'Mobile banking'],
    MojoMula: ['Mojo money', 'Mojo Mula', 'MOJO MULA'],
    MoMo: ['MoMo', 'MOMO', 'MoMo pay', 'MTN MOMO', 'MTNMOMO'],
    MoneyGram: ['Moneygram', 'Money Gram', 'MoneyGram', 'Money grame'],
    'M-Pesa': [
        'AbesafaricomMpesa Transfers',
        'AbeSafaricomMpesaTransfers',
        'mpesa',
        'M pesa',
        'M-pesa',
        'Mpesa',
        'M Pesa',
        'M-Pesa',
        'MPesa',
        'M PESA',
        'M-PESA',
        'MPESA',
        'M-Pesa Tigo-Pesa T-Pesa',
        'Pesa',
        'safaricom mpesa',
    ],
    'MTN Mobile Money': [
        'AIRTEL MOBILE MONEY',
        'all mobile money',
        'Mobile money',
        'Mobile Money',
        'Mobile money MTN',
        'Mobile Money transfer',
        'MOBILE MONEY TRANSFER',
        'MTN',
        'MTN mobile money',
        'MTN Mobile money',
        'MTN Mobile Money',
        'MTN MOBILE MONEY',
        'MTNMOBILEMONEY',
        'MTN MOMO',
        'MTNMOMO',
        'MTN MONEY',
        'TIGO MOBILE MONEY',
        'TIGOMOBILEMONEY',
    ],
    Mukuru: ['Mukuru', 'Mukuru money transfers'],
    Neft: ['neft', 'Neft', 'NEFT'],
    Neteller: ['neTeller', 'Neteller', 'NETELLER'],
    'Nigeria local bank': ['Nigeria Local', 'Nigeria local bank', 'NIGERIA LOCAL BANK'],
    OneMoney: ['Onemoney', 'One Money', 'One money service'],
    Opay: ['Opay', 'OPAY'],
    'Orange Money': [
        'Absa fund transfer and orange money services',
        'orange money',
        'orangemoney',
        'Orange money',
        'Orangemoney',
        'Orange Money',
        'OrangeMoney',
        'ORANGE MONEY',
        'Orange Money Transfer',
    ],
    'Pay 2 Cell': [
        'FNB pay2cell',
        'FNB pay to cell',
        'FNB pay to sell',
        'Pay2cell',
        'Pay2Cell',
        'PAY2CELL',
        'pay to cell',
        'Pay to cell',
        'Paytocell',
        'Pay to Cell',
        'Pay to cell FNB',
    ],
    'Payment Checks': ['Payment checks', 'Payment Checks'],
    PayPal: [
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'Paypal',
        'PayPal',
        'PAYPAL',
    ],
    Paytm: ['Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe', 'Paytm', 'PayTM'],
    Paysafecard: ['paysafecard', 'Pay safe Card'],
    'Perfect Money': [
        'Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe',
        'perfect money',
        'perfectmoney',
        'Perfect money',
        'Perfectmoney',
        'Perfect Money',
        'PerfectMoney',
        'PERFECT MONEY',
        'Perfect Money and Webmoney',
    ],
    Phonepe: ['phonepe', 'Phonepe', 'PhonePe'],
    PhonePhe: ['Banks BHIMUP BTC Ewallet GooglePay LocalBank Paypal Paytm Perfect Money PhonePhe'],
    Pix: ['Pix', 'PIX'],
    'Ponto 24': ['Ponto 24', 'Ponto24'],
    POS: ['Pos', 'POS', 'Pos deposit'],
    RIA: ['Ria', 'RIA'],
    'RTGS Bank': ['rtgs', 'RTGS', 'Rtgs bank transfer', 'RTGS transfers'],
    Safaricom: ['AbesafaricomMpesa Transfers', 'AbeSafaricomMpesaTransfers', 'safaricom mpesa'],
    Skrill: ['Skill', 'Skril', 'skrill', 'SKRILL', 'skrillpayments', 'Skrll'],
    Smega: ['btc smega', 'smega', 'Smega'],
    Stanbic: [
        'stanbic',
        'Stanbic',
        'Stanbic Bank',
        'StanbicBank',
        'Stanbic Bank Transfer',
        'Stanbic Money Transfer',
        'Instant money stanbic',
        'Standbic',
    ],
    'Standard Charted Bank': [
        'Standard Charted Bank',
        'Standard chartered',
        'Standard chartered bank',
        'Standard Chartered Bank Transfer',
        'Standard Chatterd Bank',
    ],
    Test: ['test', 'Test'],
    Tigo: [
        'Airtel Tigo',
        'M-Pesa Tigo-Pesa T-Pesa',
        'Tigo',
        'Tigo Cash',
        'TIGO MOBILE MONEY',
        'TIGOMOBILEMONEY',
        'tigopesa',
        'Tigo pesa',
        'Tigopesa',
        'Tigo Pesa',
        'TigoPesa',
        'TIGO PESA',
        'T-pesa',
        'Tpesa',
        'T PESA',
    ],
    'Transferencia bancaria': ['Transferencia bancaria', 'Transferencias bancarias'],
    'UBA Bank': ['UBA', 'UBA Bank', 'UBA BANK'],
    'Union Bank': ['Union Bank', 'Unionbank'],
    UPI: ['All UPI Transfer', 'upi', 'UPI', 'UPI transfer'],
    USD: ['USD', 'USD cash'],
    'USSD Code': [
        'USSD Code',
        'USSD CODE',
        'Ussd code Transfer from all Nigerian banks',
        'Ussd transfer',
        'USSD transfer',
    ],
    Visa: ['Millenium Bim Visa', 'visa', 'Visa', 'VISA', 'Visa card'],
    'Vodafone Cash': ['Vodafon Cash Methods', 'Vodafone cash', 'Vodafone Cash', 'VODAFONE CASH', 'VODAFONECASH'],
    WebMoney: ['Perfect Money and Webmoney', 'Webmoney', 'WebMoney'],
    'Western Union': ['Western union', 'Western Union', 'WesternUnion'],
    'World Remit': ['World remit', 'World Remit'],
    'Zanaco bank': ['ZANACO', 'Zanaco bank'],
    'Zenith Bank': ['Zenith bank', 'Zenithbank', 'Zenith Bank', 'ZenithBank', 'ZENITH BANK'],
    ZIPIT: ['Zipit', 'ZIPIT', 'ZIPIT bank transfers'],
    ZWL: ['All local banks ZWL', 'Ecocash ZWL'],
};

export default { containers, map_action, icon_payment_methods, payment_methods };
