type TWalletTypes = {
    [key: string]: {
        color: string;
        icon: string;
    };
};
export const wallets: TWalletTypes = {
    '1Foryou': { color: '#FF5F00', icon: '1foryou' },
    Advcash: { color: '#00AF7E', icon: 'Advcash' },
    Airtm: { color: '#1A8FFF', icon: 'Airtm' },
    Astropay: { color: '#FF0000', icon: 'Astropay' },
    'Bank wire': { color: '#93A6AD', icon: 'BankWire' },
    Banxa: { color: '#23BDAE', icon: 'Banxa' },
    Beyonic: { color: '#B6CDED', icon: 'Beyonic' },
    Bitcoin: { color: '#F7931B', icon: 'Bitcoin' },
    Boleto: { color: '#333333', icon: 'Boleto' },
    Changelly: { color: '#10D078', icon: 'Changelly' },
    'Credit cards': { color: '#3C58C6', icon: 'CreditCards' },
    Demo: { color: '#1A8FFF', icon: 'Demo' },
    'Deriv P2P': { color: '#FF444F', icon: 'DerivP2p' },
    'Diners Club': { color: '#184977', icon: 'DinersClub' },
    Ethereum: { color: '#52567F', icon: 'Ethereum' },
    Fasapay: { color: '#F6931C', icon: 'Fasapay' },
    Help2pay: { color: '#A9C51A', icon: 'Help2pay' },
    JCB: { color: '#016AB6', icon: 'Jcb' },
    Jeton: { color: '#FF671F', icon: 'Jeton' },
    Litecoin: { color: '#A5A8A9', icon: 'Litecoin' },
    Maestro: { color: '#EB001B', icon: 'Maestro' },
    Mastercard: { color: '#EB001B', icon: 'Mastercard' },
    Neteller: { color: '#8DC640', icon: 'Neteller' },
    Nganluong: { color: '#E87701', icon: 'Nganluong' },
    OnlineNaira: { color: '#008751', icon: 'Onlinenaira' },
    OXXO: { color: '#E20613', icon: 'Oxxo' },
    'Pay Livre': { color: '#9A6BFC', icon: 'PayLivre' },
    'Payment agent': { color: '#979797', icon: 'PaymentAgent' },
    'Paysafe card': { color: '#008AC9', icon: 'Paysafecard' },
    Paytrust88: { color: '#F3BA0C', icon: 'Paytrust88' },
    'Perfect Money': { color: '#EF1515', icon: 'PerfectMoney' },
    Skrill: { color: '#6C2556', icon: 'Skrill' },
    SPEI: { color: '#303992', icon: 'Spei' },
    Sticpay: { color: '#F25822', icon: 'Sticpay' },
    Tether: { color: '#009393', icon: 'Tether' },
    Trustly: { color: '#0EE06E', icon: 'Trustly' },
    'USD Coin': { color: '#2775CA', icon: 'UsdCoin' },
    Visa: { color: '#1A1F71', icon: 'Visa' },
    'Visa Electron': { color: '#1A1F71', icon: 'VisaElectron' },
    WebMoney: { color: '#0068A3', icon: 'Webmoney' },
    'WeChat Pay': { color: '#39A935', icon: 'WechatPay' },
    Zingpay: { color: '#A8E2C1', icon: 'Zingpay' },
};
