export const wallets = [
    { name: '1Foryou', color: '#FF5F00' },
    { name: 'Advcash', color: '#00AF7E' },
    { name: 'Airtm', color: '#1A8FFF' },
    { name: 'Astropay', color: '#FF0000' },
    { name: 'Bank wire', color: '#93A6AD' },
    { name: 'Banxa', color: '#23BDAE' },
    { name: 'Beyonic', color: '#B6CDED' },
    { name: 'Bitcoin', color: '#F7931B' },
    { name: 'Boleto', color: '#333333' },
    { name: 'Changelly', color: '#10D078' },
    { name: 'Credit cards', color: '#3C58C6' },
    { name: 'Demo', color: '#1A8FFF' },
    { name: 'Deriv P2P', color: '#FF444F' },
    { name: 'Diners Club', color: '#184977' },
    { name: 'Ethereum', color: '#52567F' },
    { name: 'Fasapay', color: '#F6931C' },
    { name: 'Help2pay', color: '#A9C51A' },
    { name: 'JCB', color: '#016AB6' },
    { name: 'Jeton', color: '#FF671F' },
    { name: 'Litecoin', color: '#A5A8A9' },
    { name: 'Maestro', color: '#EB001B' },
    { name: 'Mastercard', color: '#EB001B' },
    { name: 'Neteller', color: '#8DC640' },
    { name: 'Nganluong', color: '#E87701' },
    { name: 'OnlineNaira', color: '#008751' },
    { name: 'OXXO', color: '#E20613' },
    { name: 'Pay Livre', color: '#9A6BFC' },
    { name: 'Payment agent', color: '#979797' },
    { name: 'Paysafe card', color: '#008AC9' },
    { name: 'Paytrust88', color: '#F3BA0C' },
    { name: 'Perfect Money', color: '#EF1515' },
    { name: 'Skrill', color: '#6C2556' },
    { name: 'SPEI', color: '#303992' },
    { name: 'Sticpay', color: '#F25822' },
    { name: 'Tether', color: '#009393' },
    { name: 'Trustly', color: '#0EE06E' },
    { name: 'USD Coin', color: '#2775CA' },
    { name: 'Visa', color: '#1A1F71' },
    { name: 'Visa Electron', color: '#1A1F71' },
    { name: 'WebMoney', color: '#0068A3' },
    { name: 'WeChat Pay', color: '#39A935' },
    { name: 'Zingpay', color: '#A8E2C1' },
];
