import {
    candleField,
    candleValues,
    checkDirection,
    dateTimeStringToTimestamp,
    isCandleBlack,
    getAskPrice,
    getBalance,
    readDetails,
    getLastDigitBinaryUtils as getLastDigit,
    getLastDigitList,
    getLastTick,
    getOhlc,
    getOhlcFromEnd,
    getTicks,
    getPayout,
    getPurchaseReference,
    getSellPrice,
    getTime,
    getTotalProfit,
    getTotalRuns,
    initTradeEngine as init,
    isResult,
    isSellAtMarketAvailable as isSellAvailable,
    isTradeAgainObserver as isTradeAgain,
    miscAlert as alert,
    miscConsole as console,
    miscPrompt as prompt,
    notify,
    notifyTelegram,
    purchase,
    sellAtMarket,
    sleep,
    startTradeEngine as start,
    stopTradeEngine as stop,
    tradeEngineObserver,
    watch,
    $scope,
    indicators,
} from './tradeEngine';

const getInterface = () => {
    return {
        alert,
        candleField,
        candleValues,
        isCandleBlack,
        console,
        dateTimeStringToTimestamp,
        getAskPrice,
        getBalance,
        getLastDigitList,
        getPayout,
        getSellPrice,
        getPurchaseReference,
        getTime,
        getTotalProfit,
        init,
        isResult,
        isSellAvailable,
        isTradeAgain,
        notify,
        notifyTelegram,
        prompt,
        purchase,
        readDetails,
        sellAtMarket,
        sleep,
        start,
        stop,
        tradeEngineObserver,
        watch,
        getTotalRuns,
        getTicksInterface: {
            checkDirection,
            getLastDigit,
            getLastDigitList,
            getLastTick,
            getOhlc,
            getOhlcFromEnd,
            getTicks,
        },
        scope: $scope,
        ...indicators,
    };
};

export default getInterface;
