export const adverts = [
    {
        account_currency: 'USD',
        advertiser_details: {
            completed_orders_count: 1,
            id: '28',
            is_blocked: 0,
            is_favourite: 0,
            is_online: 1,
            is_recommended: null,
            last_online_time: 1686297513,
            name: 'am1',
            rating_average: 4,
            rating_count: 1,
            recommended_average: null,
            recommended_count: null,
            total_completion_rate: 50,
        },
        counterparty_type: 'buy',
        country: 'id',
        created_time: 1686020292,
        description: 'Created by script. Please call me 02203400',
        effective_rate: 13500,
        effective_rate_display: '13500.00',
        id: '53',
        is_active: 1,
        is_visible: 1,
        local_currency: 'IDR',
        max_order_amount_limit: 49.8,
        max_order_amount_limit_display: '49.80',
        min_order_amount_limit: 0.1,
        min_order_amount_limit_display: '0.10',
        order_expiry_period: 3600,
        payment_method: 'bank_transfer',
        payment_method_details: { 1: { display_name: 'Bank Transfer', method: 'bank_transfer', type: 'bank' } },
        payment_method_names: ['Bank Transfer'],
        price: 13500,
        price_display: '13500.00',
        rate: 13500,
        rate_display: '13500.00',
        rate_type: 'fixed',
        type: 'sell',
    },
];
