import {
    AMOUNT_MAX_LENGTH,
    formatMoney,
    formatCurrency,
    addComma,
    getDecimalPlaces,
    setCurrencies,
    isCryptocurrency,
    getCurrencyDisplayCode,
    getCurrencyName,
    getMinWithdrawal,
    getTransferLimits,
    getTransferFee,
    getMinimumTransferFee,
    getFormattedText,
    getRoundedNumber,
    getMinPayout,
    getPaWithdrawalLimit,
    getCurrencies,
} from './currency';

export default {
    AMOUNT_MAX_LENGTH,
    formatMoney,
    formatCurrency,
    addComma,
    getDecimalPlaces,
    setCurrencies,
    isCryptocurrency,
    getCurrencyDisplayCode,
    getCurrencyName,
    getMinWithdrawal,
    getTransferLimits,
    getTransferFee,
    getMinimumTransferFee,
    getFormattedText,
    getRoundedNumber,
    getMinPayout,
    getPaWithdrawalLimit,
    getCurrencies,
};
