name: Deriv App Integration Test Workflow
on:
  pull_request:
    branches:
    - master
  push:
    branches:
      - master
jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: Runner_8cores_Deriv-app
    environment: Preview
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install dependencies
      uses: "./.github/actions/npm_install_from_cache"
    - name: Invalidate NPM Cache
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: "./.github/actions/invalidate_npm_cache"
    - name: Build
      run: npm run build:all
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run component tests
      run: npm run test:component
