name: Update NX cache

on:
  push:
    branches:
    - master

jobs:
  build_cache:
    name: Build cache
    runs-on: Runner_8cores_Deriv-app
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Cache NX cache
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-cache-${{ hashFiles('nx.json', 'package-lock.json', 'packages/*/package.json') }}
      - if: ${{ steps.cache-nx.outputs.cache-hit != 'true' }}
        name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"


