name: Update node modules cache

on:
  push:
    branches:
    - master

jobs:
  build_cache:
    name: Build cache
    runs-on: Runner_16cores_Deriv-app
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node_modules-cache-${{ hashFiles('package-lock.json', 'packages/*/package.json') }}
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
